### ISSUE TITLE
Link retorna 404 - Documento de avaliação na wiki

### ISSUE THREAD

**Issue by ErickGiffoni** [Interacao-Humano-Computador/2020.1-CD-MOJ#28]
Olá, pessoal, na wiki, em Avaliação do storyboard, tópico 2, existe um link para um
documento de avaliação, porém ele retorna 404.

Algo pontual, nada demais.

ABS.

**Comment by ErickGiffoni** [comment]
Está aqui, o que foi comentado acima: https://interacao-humano-computador.github.io/2020.1-CD-MOJ/DeAD/nivel1/avaliacao_storyboard/#2-avaliacao

**Comment by igor-paiva** [comment]
Obrigado pelo feedback
